version: '3'

services: 
  node1: 
    image: localhost:5000/myjenkins
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - jenkinscluster
  node2:
    image: localhost:5000/myjenkins
    ports: 
      - 8082:8080
      - 50002:50000
    networks:
      - jenkinscluster
  node3:
    image: localhost:5000/myjenkins
    ports:
      - 8083:8080
      - 50003:50000
networks:
  jenkinscluster: 
    driver: bridge        
